<?php

function getWeaponsArray() {
	$weaponsArray = [
        array(
            "name" => "Arquebus",
            "size" => "M",
            "type" => "P",
            "speed" => 15,
            "damageSM" => "1d10",
            "damageL" => "1d10",
            "rof" => "1/3",
            "rangeS" => "50",
            "rangeM" => "150",
            "rangeL" => "210",
        ),

        array(
            "name" => "Battle Axe",
            "size" => "M",
            "type" => "S",
            "speed" => 7,
            "damageSM" => "1d8",
            "damageL" => "1d8",
            "rof" => "n/a",
            "rangeS" => "n/a",
            "rangeM" => "n/a",
            "rangeL" => "n/a",
        ),

        array(
            "name" => "Blowgun w/ Barbed Dart",
            "size" => "S",
            "type" => "P",
            "speed" => 5,
            "damageSM" => "1d3",
            "damageL" => "1d2",
            "rof" => "2/1",
            "rangeS" => "10",
            "rangeM" => "20",
            "rangeL" => "30",
        ),

        array(
            "name" => "Blowgun w/ Needle",
            "size" => "S",
            "type" => "P",
            "speed" => 5,
            "damageSM" => "1",
            "damageL" => "1",
            "rof" => "2/1",
            "rangeS" => "10",
            "rangeM" => "20",
            "rangeL" => "30",
        ),

        array(
            "name" => "Short Bow w/ Sheaf Arrow",
            "size" => "M",
            "type" => "P",
            "speed" => 7,
            "damageSM" => "1d8",
            "damageL" => "1d8",
            "rof" => "2/1",
            "rangeS" => "50",
            "rangeM" => "100",
            "rangeL" => "150",
        ),

        array(
            "name" => "Long Bow w/ Sheaf Arrow",
            "size" => "L",
            "type" => "P",
            "speed" => 8,
            "damageSM" => "1d8",
            "damageL" => "1d8",
            "rof" => "2/1",
            "rangeS" => "50",
            "rangeM" => "100",
            "rangeL" => "170",
        ),

        array(
            "name" => "Long Bow w/ Flight Arrow",
            "size" => "L",
            "type" => "P",
            "speed" => 8,
            "damageSM" => "1d6",
            "damageL" => "1d6",
            "rof" => "2/1",
            "rangeS" => "70",
            "rangeM" => "140",
            "rangeL" => "210",
        ),

        array(
            "name" => "Composite Short Bow w/ Sheaf Arrow",
            "size" => "M",
            "type" => "P",
            "speed" => 6,
            "damageSM" => "1d8",
            "damageL" => "1d8",
            "rof" => "2/1",
            "rangeS" => "50",
            "rangeM" => "100",
            "rangeL" => "180",
        ),

        array(
            "name" => "Composite Long Bow w/ Sheaf Arrow",
            "size" => "L",
            "type" => "P",
            "speed" => 7,
            "damageSM" => "1d8",
            "damageL" => "1d8",
            "rof" => "2/1",
            "rangeS" => "40",
            "rangeM" => "80",
            "rangeL" => "170",
        ),

        array(
            "name" => "Composite Long Bow w/ Flight Arrow",
            "size" => "L",
            "type" => "P",
            "speed" => 7,
            "damageSM" => "1d6",
            "damageL" => "1d6",
            "rof" => "2/1",
            "rangeS" => "60",
            "rangeM" => "120",
            "rangeL" => "210",
        ),

        array(
            "name" => "Club",
            "size" => "M",
            "type" => "B",
            "speed" => 4,
            "damageSM" => "1d6",
            "damageL" => "1d3",
            "rof" => "n/a",
            "rangeS" => "n/a",
            "rangeM" => "n/a",
            "rangeL" => "n/a",
        ),

        array(
            "name" => "Hand Crossbow",
            "size" => "S",
            "type" => "P",
            "speed" => 5,
            "damageSM" => "1d3",
            "damageL" => "1d2",
            "rof" => "1",
            "rangeS" => "20",
            "rangeM" => "40",
            "rangeL" => "60",
        ),

        array(
            "name" => "Light Crossbow",
            "size" => "M",
            "type" => "P",
            "speed" => 7,
            "damageSM" => "1d4",
            "damageL" => "1d4",
            "rof" => "1",
            "rangeS" => "60",
            "rangeM" => "120",
            "rangeL" => "180",
        ),

        array(
            "name" => "Heavy Crossbow",
            "size" => "M",
            "type" => "P",
            "speed" => 10,
            "damageSM" => "1d4+1",
            "damageL" => "1d6+1",
            "rof" => "1/2",
            "rangeS" => "80",
            "rangeM" => "160",
            "rangeL" => "240",
        ),

        array(
            "name" => "Dagger",
            "size" => "S",
            "type" => "P",
            "speed" => 2,
            "damageSM" => "1d4",
            "damageL" => "1d3",
            "rof" => "n/a",
            "rangeS" => "n/a",
            "rangeM" => "n/a",
            "rangeL" => "n/a",
        ),

        array(
            "name" => "Dirk",
            "size" => "S",
            "type" => "P",
            "speed" => 2,
            "damageSM" => "1d4",
            "damageL" => "1d3",
            "rof" => "n/a",
            "rangeS" => "n/a",
            "rangeM" => "n/a",
            "rangeL" => "n/a",
        ),

        array(
            "name" => "Dart",
            "size" => "S",
            "type" => "P",
            "speed" => 2,
            "damageSM" => "1d3",
            "damageL" => "1d2",
            "rof" => "3/1",
            "rangeS" => "10",
            "rangeM" => "20",
            "rangeL" => "40",
        ),

        array(
            "name" => "Footman's Flail",
            "size" => "M",
            "type" => "B",
            "speed" => 7,
            "damageSM" => "1d6+1",
            "damageL" => "2d4",
            "rof" => "n/a",
            "rangeS" => "n/a",
            "rangeM" => "n/a",
            "rangeL" => "n/a",
        ),

        array(
            "name" => "Footman's Mace",
            "size" => "M",
            "type" => "B",
            "speed" => 7,
            "damageSM" => "1d6+1",
            "damageL" => "1d6",
            "rof" => "n/a",
            "rangeS" => "n/a",
            "rangeM" => "n/a",
            "rangeL" => "n/a",
        ),

        array(
            "name" => "Footman's Pick",
            "size" => "M",
            "type" => "P",
            "speed" => 7,
            "damageSM" => "1d6+1",
            "damageL" => "2d4",
            "rof" => "n/a",
            "rangeS" => "n/a",
            "rangeM" => "n/a",
            "rangeL" => "n/a",
        ),

        array(
            "name" => "Hand Axe / Throwing Axe",
            "size" => "M",
            "type" => "S",
            "speed" => 4,
            "damageSM" => "1d6",
            "damageL" => "1d4",
            "rof" => "1",
            "rangeS" => "10",
            "rangeM" => "20",
            "rangeL" => "30",
        ),

        array(
            "name" => "Harpoon",
            "size" => "L",
            "type" => "P",
            "speed" => 7,
            "damageSM" => "2d4",
            "damageL" => "2d6",
            "rof" => "1",
            "rangeS" => "10",
            "rangeM" => "20",
            "rangeL" => "30",
        ),

        array(
            "name" => "Horseman's Flail",
            "size" => "M",
            "type" => "B",
            "speed" => 6,
            "damageSM" => "1d4+1",
            "damageL" => "1d4+1",
            "rof" => "n/a",
            "rangeS" => "n/a",
            "rangeM" => "n/a",
            "rangeL" => "n/a",
        ),

        array(
            "name" => "Horseman's Mace",
            "size" => "M",
            "type" => "B",
            "speed" => 6,
            "damageSM" => "1d6",
            "damageL" => "1d4",
            "rof" => "n/a",
            "rangeS" => "n/a",
            "rangeM" => "n/a",
            "rangeL" => "n/a",
        ),

        array(
            "name" => "Horseman's Pick",
            "size" => "M",
            "type" => "P",
            "speed" => 5,
            "damageSM" => "1d4+1",
            "damageL" => "1d4",
            "rof" => "n/a",
            "rangeS" => "n/a",
            "rangeM" => "n/a",
            "rangeL" => "n/a",
        ),

        array(
            "name" => "Javelin",
            "size" => "M",
            "type" => "P",
            "speed" => 4,
            "damageSM" => "1d6",
            "damageL" => "1d6",
            "rof" => "1",
            "rangeS" => "20",
            "rangeM" => "40",
            "rangeL" => "60",
        ),

        array(
            "name" => "Knife",
            "size" => "S",
            "type" => "P/S",
            "speed" => 2,
            "damageSM" => "1d3",
            "damageL" => "1d2",
            "rof" => "2/1",
            "rangeS" => "10",
            "rangeM" => "20",
            "rangeL" => "30",
        ),

        array(
            "name" => "Heavy Horse Lance",
            "size" => "L",
            "type" => "P",
            "speed" => 8,
            "damageSM" => "1d8+1",
            "damageL" => "3d6",
            "rof" => "n/a",
            "rangeS" => "n/a",
            "rangeM" => "n/a",
            "rangeL" => "n/a",
        ),

        array(
            "name" => "Light Horse Lance",
            "size" => "L",
            "type" => "P",
            "speed" => 6,
            "damageSM" => "1d6",
            "damageL" => "1d8",
            "rof" => "n/a",
            "rangeS" => "n/a",
            "rangeM" => "n/a",
            "rangeL" => "n/a",
        ),

        array(
            "name" => "Jousting Lance",
            "size" => "L",
            "type" => "P",
            "speed" => 10,
            "damageSM" => "1d3-1",
            "damageL" => "1d2-1",
            "rof" => "n/a",
            "rangeS" => "n/a",
            "rangeM" => "n/a",
            "rangeL" => "n/a",
        ),

        array(
            "name" => "Medium Horse Lance",
            "size" => "L",
            "type" => "P",
            "speed" => 7,
            "damageSM" => "1d6+1",
            "damageL" => "2d6",
            "rof" => "n/a",
            "rangeS" => "n/a",
            "rangeM" => "n/a",
            "rangeL" => "n/a",
        ),

        array(
            "name" => "Mancatcher",
            "size" => "L",
            "type" => "n/a",
            "speed" => 7,
            "damageSM" => "n/a",
            "damageL" => "n/a",
            "rof" => "n/a",
            "rangeS" => "n/a",
            "rangeM" => "n/a",
            "rangeL" => "n/a",
        ),

        array(
            "name" => "Morning Star",
            "size" => "M",
            "type" => "P/B",
            "speed" => 7,
            "damageSM" => "2d4",
            "damageL" => "1d6+1",
            "rof" => "n/a",
            "rangeS" => "n/a",
            "rangeM" => "n/a",
            "rangeL" => "n/a",
        ),

    ];
    return $weaponsArray;
}

?>
